name: task_3

services:
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - path: .env
        required: true
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      retries: 5
networks:
  backend:
    driver: bridge

volumes:
  postgres:
  redis_data:
    driver: local